image: node:14

pages:
  script:
    - set -e
    - npm install
    - npm run generate
    - cp -r dist public
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'

purge_cache:
  stage: .post
  script:
    - |
      curl "https://api.cloudflare.com/client/v4/zones/${CF_ZONE}/purge_cache" \
        -H 'X-Auth-Email: ${CF_EMAIL}' \
        -H 'X-Auth-key: ${CF_PURGE_KEY}'
