image: node:14

pages:
  script:
    - npm install
    - npm run build
    - npm run generate
    - cp -r dist public
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
